export const siteMap = {
  Buttons: "components/button/button.html",
  "Side Nav": "components/side-nav/side-nav.html",
  Search: "components/search/search.html",
  Checkbox: "components/form/checkbox/checkbox.html",
  Radio: "components/form/radio/radio.html",
  Switch: "components/form/switch/Switch.html",
  "Text input": "components/form/text-input/text-input.html",
  "Text area": "components/form/text-area/text-area.html",
  Dropdown: "components/form/dropdown/dropdown.html",
  "Multi Select": "components/form/multi-select/multi-select.html",
  "Auto Complete": "components/form/autocomplete/autocomplete.html",
  Chips: "components/form/chips/chips.html",
  Slider: "components/slider/slider.html",
  "Page Drawer": "components/page-drawer/page-drawer.html",
  Tabs: "components/tabs/tabs.html",
  Tag: "components/tag/tag.html",
  "Inline Notification": "components/notification/inline-notification.html",
  "Toast Notification": "components/notification/toast-notification.html",
  Tooltip: "components/tooltip/tooltip.html",
  Popover: "components/popover/popover.html",
  Card: "components/card/card.html",
  "Scroll Area": "components/scroll-area/scroll-area.html",
  Modal: "components/modal/modal.html",
};
