export const siteMap = {
  Accordion: "components/accordion/accordion.html",
  Buttons: "components/button/button.html",
  "Side Nav": "components/side-nav/side-nav.html",
  Search: "components/search/search.html",
  Checkbox: "components/form/checkbox/checkbox.html",
  Radio: "components/form/radio/radio.html",
  Switch: "components/form/switch/Switch.html",
  "Toggle Buttons": "components/form/toggle-buttons/toggle-buttons.html",
  "Text input": "components/form/text-input/text-input.html",
  "Text area": "components/form/text-area/text-area.html",
  "Number Input": "components/form/number-input/number-input.html",
  Dropdown: "components/form/dropdown/dropdown.html",
  "Multi Select": "components/form/multi-select/multi-select.html",
  "Auto Complete": "components/form/autocomplete/autocomplete.html",
  Chips: "components/form/chips/chips.html",
  Slider: "components/slider/slider.html",
  "Page Drawer": "components/page-drawer/page-drawer.html",
  Tabs: "components/tabs/tabs.html",
  Tag: "components/tag/tag.html",
  "Inline Notification": "components/notification/inline-notification.html",
  "Toast Notification": "components/notification/toast-notification.html",
  Tooltip: "components/tooltip/tooltip.html",
  Popover: "components/popover/popover.html",
  "Overflow Menu": "components/overflow-menu/overflow-menu.html",
  Card: "components/card/card.html",
  "Scroll Area": "components/scroll-area/scroll-area.html",
  Modal: "components/modal/modal.html",
  "Data Table": "components/data-table/data-table.html",
  List: "components/list/list.html",
  Pagination: "components/pagination/pagination.html",
  "Proggress Indicator":
    "components/progress-indicator/progress-indicator.html",
  "Date Picker": "components/date-picker/date-picker.html",
};
